extends Node

enum {
	BACK,
	BLANK,
	CLUB_2,
	CLUB_3,
	CLUB_4,
	CLUB_5,
	CLUB_6,
	CLUB_7,
	CLUB_8,
	CLUB_9,
	CLUB_10,
	CLUB_J,
	CLUB_Q,
	CLUB_K,
	CLUB_ACE,
	DIAMOND_2,
	DIAMOND_3,
	DIAMOND_4,
	DIAMOND_5,
	DIAMOND_6,
	DIAMOND_7,
	DIAMOND_8,
	DIAMOND_9,
	DIAMOND_10,
	DIAMOND_J,
	DIAMOND_Q,
	DIAMOND_K,
	DIAMOND_ACE,
	HEART_2,
	HEART_3,
	HEART_4,
	HEART_5,
	HEART_6,
	HEART_7,
	HEART_8,
	HEART_9,
	HEART_10,
	HEART_J,
	HEART_Q,
	HEART_K,
	HEART_ACE,
	SPADE_2,
	SPADE_3,
	SPADE_4,
	SPADE_5,
	SPADE_6,
	SPADE_7,
	SPADE_8,
	SPADE_9,
	SPADE_10,
	SPADE_J,
	SPADE_Q,
	SPADE_K,
	SPADE_ACE,
	JESTER_1,
	JESTER_2,
	JESTER_3,
	JESTER_4,
	WIZARD_1,
	WIZARD_2,
	WIZARD_3,
	WIZARD_4,
}

const DATA = [
	{
		"suite": null,
		"rank": null,
		"image": "res://assets/gui/cards/back.png",
	},
	{
		"suite": null,
		"rank": null,
		"image": "res://assets/gui/cards/blank.png",
	},
	{
		"suite": "club",
		"rank": 2,
		"image": "res://assets/gui/cards/club_2.png",
	},
	{
		"suite": "club",
		"rank": 3,
		"image": "res://assets/gui/cards/club_3.png",
	},
	{
		"suite": "club",
		"rank": 4,
		"image": "res://assets/gui/cards/club_4.png",
	},
	{
		"suite": "club",
		"rank": 5,
		"image": "res://assets/gui/cards/club_5.png",
	},
	{
		"suite": "club",
		"rank": 6,
		"image": "res://assets/gui/cards/club_6.png",
	},
	{
		"suite": "club",
		"rank": 7,
		"image": "res://assets/gui/cards/club_7.png",
	},
	{
		"suite": "club",
		"rank": 8,
		"image": "res://assets/gui/cards/club_8.png",
	},
	{
		"suite": "club",
		"rank": 9,
		"image": "res://assets/gui/cards/club_9.png",
	},
	{
		"suite": "club",
		"rank": 10,
		"image": "res://assets/gui/cards/club_10.png",
	},
	{
		"suite": "club",
		"rank": 11,
		"image": "res://assets/gui/cards/club_j.png",
	},
	{
		"suite": "club",
		"rank": 12,
		"image": "res://assets/gui/cards/club_q.png",
	},
	{
		"suite": "club",
		"rank": 13,
		"image": "res://assets/gui/cards/club_k.png",
	},
	{
		"suite": "club",
		"rank": 14,
		"image": "res://assets/gui/cards/club_ace.png",
	},
	{
		"suite": "heart",
		"rank": 2,
		"image": "res://assets/gui/cards/heart_2.png",
	},
	{
		"suite": "heart",
		"rank": 3,
		"image": "res://assets/gui/cards/heart_3.png",
	},
	{
		"suite": "heart",
		"rank": 4,
		"image": "res://assets/gui/cards/heart_4.png",
	},
	{
		"suite": "heart",
		"rank": 5,
		"image": "res://assets/gui/cards/heart_5.png",
	},
	{
		"suite": "heart",
		"rank": 6,
		"image": "res://assets/gui/cards/heart_6.png",
	},
	{
		"suite": "heart",
		"rank": 7,
		"image": "res://assets/gui/cards/heart_7.png",
	},
	{
		"suite": "heart",
		"rank": 8,
		"image": "res://assets/gui/cards/heart_8.png",
	},
	{
		"suite": "heart",
		"rank": 9,
		"image": "res://assets/gui/cards/heart_9.png",
	},
	{
		"suite": "heart",
		"rank": 10,
		"image": "res://assets/gui/cards/heart_10.png",
	},
	{
		"suite": "heart",
		"rank": 11,
		"image": "res://assets/gui/cards/heart_j.png",
	},
	{
		"suite": "heart",
		"rank": 12,
		"image": "res://assets/gui/cards/heart_q.png",
	},
	{
		"suite": "heart",
		"rank": 13,
		"image": "res://assets/gui/cards/heart_k.png",
	},
	{
		"suite": "heart",
		"rank": 14,
		"image": "res://assets/gui/cards/heart_ace.png",
	},
	{
		"suite": "spade",
		"rank": 2,
		"image": "res://assets/gui/cards/spades_2.png",
	},
	{
		"suite": "spade",
		"rank": 3,
		"image": "res://assets/gui/cards/spades_3.png",
	},
	{
		"suite": "spade",
		"rank": 4,
		"image": "res://assets/gui/cards/spades_4.png",
	},
	{
		"suite": "spade",
		"rank": 5,
		"image": "res://assets/gui/cards/spades_5.png",
	},
	{
		"suite": "spade",
		"rank": 6,
		"image": "res://assets/gui/cards/spades_6.png",
	},
	{
		"suite": "spade",
		"rank": 7,
		"image": "res://assets/gui/cards/spades_7.png",
	},
	{
		"suite": "spade",
		"rank": 8,
		"image": "res://assets/gui/cards/spades_8.png",
	},
	{
		"suite": "spade",
		"rank": 9,
		"image": "res://assets/gui/cards/spades_9.png",
	},
	{
		"suite": "spade",
		"rank": 10,
		"image": "res://assets/gui/cards/spades_10.png",
	},
	{
		"suite": "spade",
		"rank": 11,
		"image": "res://assets/gui/cards/spades_j.png",
	},
	{
		"suite": "spade",
		"rank": 12,
		"image": "res://assets/gui/cards/spades_q.png",
	},
	{
		"suite": "spade",
		"rank": 13,
		"image": "res://assets/gui/cards/spades_k.png",
	},
	{
		"suite": "spade",
		"rank": 14,
		"image": "res://assets/gui/cards/spades_ace.png",
	},
	{
		"suite": "diamond",
		"rank": 2,
		"image": "res://assets/gui/cards/diamond_2.png",
	},
	{
		"suite": "diamond",
		"rank": 3,
		"image": "res://assets/gui/cards/diamond_3.png",
	},
	{
		"suite": "diamond",
		"rank": 4,
		"image": "res://assets/gui/cards/diamond_4.png",
	},
	{
		"suite": "diamond",
		"rank": 5,
		"image": "res://assets/gui/cards/diamond_5.png",
	},
	{
		"suite": "diamond",
		"rank": 6,
		"image": "res://assets/gui/cards/diamond_6.png",
	},
	{
		"suite": "diamond",
		"rank": 7,
		"image": "res://assets/gui/cards/diamond_7.png",
	},
	{
		"suite": "diamond",
		"rank": 8,
		"image": "res://assets/gui/cards/diamond_8.png",
	},
	{
		"suite": "diamond",
		"rank": 9,
		"image": "res://assets/gui/cards/diamond_9.png",
	},
	{
		"suite": "diamond",
		"rank": 10,
		"image": "res://assets/gui/cards/diamond_10.png",
	},
	{
		"suite": "diamond",
		"rank": 11,
		"image": "res://assets/gui/cards/diamond_j.png",
	},
	{
		"suite": "diamond",
		"rank": 12,
		"image": "res://assets/gui/cards/diamond_q.png",
	},
	{
		"suite": "diamond",
		"rank": 13,
		"image": "res://assets/gui/cards/diamond_k.png",
	},
	{
		"suite": "diamond",
		"rank": 14,
		"image": "res://assets/gui/cards/diamond_ace.png",
	},
	{
		"suite": "jester",
		"rank": 0,
		"image": "res://assets/gui/cards/jester_1.png",
	},
	{
		"suite": "jester",
		"rank": 0,
		"image": "res://assets/gui/cards/jester_2.png",
	},
	{
		"suite": "jester",
		"rank": 0,
		"image": "res://assets/gui/cards/jester_3.png",
	},
	{
		"suite": "jester",
		"rank": 0,
		"image": "res://assets/gui/cards/jester_4.png",
	},
	{
		"suite": "wizard",
		"rank": 15,
		"image": "res://assets/gui/cards/wizard_1.png",
	},
	{
		"suite": "wizard",
		"rank": 15,
		"image": "res://assets/gui/cards/wizard_2.png",
	},
	{
		"suite": "wizard",
		"rank": 15,
		"image": "res://assets/gui/cards/wizard_3.png",
	},
	{
		"suite": "wizard",
		"rank": 15,
		"image": "res://assets/gui/cards/wizard_4.png",
	},
]
